use ova_db;

insert into courses 
values 
(100, ""),
(1, "Engenharia de Computação"),
(2, "Engenharia de Controle e Automação"),
(3, "Engenharia Química"),
(4, "Engenharia Elétrica"),
(5, "Engenharia de Produção"),
(6, "Engenharia Civil"),
(7, "Engenharia Mecânica"),
(8, "Arquitetura e Urbanismo");

insert into course_subjects
values
(1, "Cálculo A"),
(2, "Metodologia da Pesquisa"),
(3, "Compiladores"),
(4, "Banco de Dados 1"),
(5, "Controle Digital Aplicado"),
(6, "Sistemas a Eventos Discretos"),
(7, "Engenharia Bioquímica"),
(8, "Projetos de Processos Químicos 2"),
(9, "Acionamentos Elétricos"),
(10, "Eletromagnetismo"),
(11, "Comércio Exterior"),
(12, "Tecnologias Digitais na Produção"),
(13, "Estruturas de Madeira"),
(14, "Obras de Terra"),
(15, "Processos de Soldagem"),
(16, "Trocadores de Calor"),
(17, "Intraestrutura Urbana"),
(18, "Design de Interiores"),
(19, "Patrimônio Histórico");

insert into offerings
values
(1, 1, 1),
(2, 1, 2),
(3, 1, 3),
(4, 1, 4),
(5, 2, 1),
(6, 2, 2),
(7, 2, 5),
(8, 2, 6),
(9, 3, 1),
(10, 3, 2),
(11, 3, 7),
(12, 3, 8),
(13, 4, 1),
(14, 4, 2),
(15, 4, 9),
(16, 4, 10),
(17, 5, 1),
(18, 5, 2),
(19, 5, 11),
(20, 5, 12),
(21, 6, 1),
(22, 6, 2),
(23, 6, 13),
(24, 6, 14),
(25, 7, 1),
(26, 7, 2),
(27, 7, 15),
(28, 7, 16),
(29, 8, 2),
(30, 8, 17),
(31, 8, 18),
(32, 8, 19);

insert into students
values
(1, "10A.047292", "Password-0", "", 100, true),
(2, "20A.752355", "Password-1", "Eduardo Fiscina Menezes Moraes", 1, false),
(3, "10Q.178487", "Password-2", "Iago Santana Alfaya", 1, false),
(4, "67Z.406178", "Password-3", "Rodrigo de Jesus Macêdo", 1, false),
(5, "42L.910086", "Password-4", "André Lucas", 1, false),
(6, "49Z.339516", "Password-5", "João Carlos", 6, false),
(7, "22G.822160", "Password-6", "Hayana Fiscina Menezes Dias", 7, false),
(8, "30F.340348", "Password-7", "Carlos Henrique de Brandão", 4, false),
(9, "50Y.102840", "Password-8", "Maria Clara Barbosa", 4, false);

insert into ovas
values
(1, "Cálculo A", 1, "Competência 1", "cálculo_a_1.html"),
(2, "Cálculo A", 1, "Competência 2", "cálculo_a_2.html"),
(3, "Cálculo A", 1, "Competência 3", "cálculo_a_3.html"),
(4, "Cálculo A", 1, "Competência 4", "cálculo_a_4.html"),
(5, "Metodologia da Pesquisa", 2, "Competência 1", "metodologia_da_pesquisa_1.html"),
(6, "Metodologia da Pesquisa", 2, "Competência 2", "metodologia_da_pesquisa_2.html"),
(7, "Metodologia da Pesquisa", 2, "Competência 3", "metodologia_da_pesquisa_3.html"),
(8, "Metodologia da Pesquisa", 2, "Competência 4", "metodologia_da_pesquisa_4.html"),
(9, "Compiladores", 3, "Competência 1", "compiladores_1.html"),
(10, "Compiladores", 3, "Competência 2", "compiladores_2.html"),
(11, "Compiladores", 3, "Competência 3", "compiladores_3.html"),
(12, "Compiladores", 3, "Competência 4", "compiladores_4.html"),
(13, "Banco de Dados 1", 4, "Competência 1", "banco_de_dados_1_1.html"),
(14, "Banco de Dados 1", 4, "Competência 2", "banco_de_dados_1_2.html"),
(15, "Banco de Dados 1", 4, "Competência 3", "banco_de_dados_1_3.html"),
(16, "Banco de Dados 1", 4, "Competência 4", "banco_de_dados_1_4.html"),
(17, "Controle Digital Aplicado", 5, "Competência 1", "controle_digital_aplicado_1.html"),
(18, "Controle Digital Aplicado", 5, "Competência 2", "controle_digital_aplicado_2.html"),
(19, "Controle Digital Aplicado", 5, "Competência 3", "controle_digital_aplicado_3.html"),
(20, "Controle Digital Aplicado", 5, "Competência 4", "controle_digital_aplicado_4.html"),
(21, "Sistemas a Eventos Discretos", 6, "Competência 1", "sistemas_a_eventos_discretos_1.html"),
(22, "Sistemas a Eventos Discretos", 6, "Competência 2", "sistemas_a_eventos_discretos_2.html"),
(23, "Sistemas a Eventos Discretos", 6, "Competência 3", "sistemas_a_eventos_discretos_3.html"),
(24, "Sistemas a Eventos Discretos", 6, "Competência 4", "sistemas_a_eventos_discretos_4.html"),
(25, "Engenharia Bioquímica", 7, "Competência 1", "engenharia_bioquímica_1.html"),
(26, "Engenharia Bioquímica", 7, "Competência 2", "engenharia_bioquímica_2.html"),
(27, "Engenharia Bioquímica", 7, "Competência 3", "engenharia_bioquímica_3.html"),
(28, "Engenharia Bioquímica", 7, "Competência 4", "engenharia_bioquímica_4.html"),
(29, "Projetos de Processos Químicos 2", 8, "Competência 1", "projetos_de_processos_químicos_2_1.html"),
(30, "Projetos de Processos Químicos 2", 8, "Competência 2", "projetos_de_processos_químicos_2_2.html"),
(31, "Projetos de Processos Químicos 2", 8, "Competência 3", "projetos_de_processos_químicos_2_3.html"),
(32, "Projetos de Processos Químicos 2", 8, "Competência 4", "projetos_de_processos_químicos_2_4.html"),
(33, "Acionamentos Elétricos", 9, "Competência 1", "acionamentos_elétricos_1.html"),
(34, "Acionamentos Elétricos", 9, "Competência 2", "acionamentos_elétricos_2.html"),
(35, "Acionamentos Elétricos", 9, "Competência 3", "acionamentos_elétricos_3.html"),
(36, "Acionamentos Elétricos", 9, "Competência 4", "acionamentos_elétricos_4.html"),
(37, "Eletromagnetismo", 10, "Competência 1", "eletromagnetismo_1.html"),
(38, "Eletromagnetismo", 10, "Competência 2", "eletromagnetismo_2.html"),
(39, "Eletromagnetismo", 10, "Competência 3", "eletromagnetismo_3.html"),
(40, "Eletromagnetismo", 10, "Competência 4", "eletromagnetismo_4.html"),
(41, "Comércio Exterior", 11, "Competência 1", "comércio_exterior_1.html"),
(42, "Comércio Exterior", 11, "Competência 2", "comércio_exterior_2.html"),
(43, "Comércio Exterior", 11, "Competência 3", "comércio_exterior_3.html"),
(44, "Comércio Exterior", 11, "Competência 4", "comércio_exterior_4.html"),
(45, "Tecnologias Digitais na Produção", 12, "Competência 1", "tecnologias_digitais_na_produção_1.html"),
(46, "Tecnologias Digitais na Produção", 12, "Competência 2", "tecnologias_digitais_na_produção_2.html"),
(47, "Tecnologias Digitais na Produção", 12, "Competência 3", "tecnologias_digitais_na_produção_3.html"),
(48, "Tecnologias Digitais na Produção", 12, "Competência 4", "tecnologias_digitais_na_produção_4.html"),
(49, "Estruturas de Madeira", 13, "Competência 1", "estruturas_de_madeira_1.html"),
(50, "Estruturas de Madeira", 13, "Competência 2", "estruturas_de_madeira_2.html"),
(51, "Estruturas de Madeira", 13, "Competência 3", "estruturas_de_madeira_3.html"),
(52, "Estruturas de Madeira", 13, "Competência 4", "estruturas_de_madeira_4.html"),
(53, "Obras de Terra", 14, "Competência 1", "obras_de_terra_1.html"),
(54, "Obras de Terra", 14, "Competência 2", "obras_de_terra_2.html"),
(55, "Obras de Terra", 14, "Competência 3", "obras_de_terra_3.html"),
(56, "Obras de Terra", 14, "Competência 4", "obras_de_terra_4.html"),
(57, "Processos de Soldagem", 15, "Competência 1", "processos_de_soldagem_1.html"),
(58, "Processos de Soldagem", 15, "Competência 2", "processos_de_soldagem_2.html"),
(59, "Processos de Soldagem", 15, "Competência 3", "processos_de_soldagem_3.html"),
(60, "Processos de Soldagem", 15, "Competência 4", "processos_de_soldagem_4.html"),
(61, "Trocadores de Calor", 16, "Competência 1", "trocadores_de_calor_1.html"),
(62, "Trocadores de Calor", 16, "Competência 2", "trocadores_de_calor_2.html"),
(63, "Trocadores de Calor", 16, "Competência 3", "trocadores_de_calor_3.html"),
(64, "Trocadores de Calor", 16, "Competência 4", "trocadores_de_calor_4.html"),
(65, "Infraestrutura Urbana", 17, "Competência 1", "infraestrutura_urbana_1.html"),
(66, "Infraestrutura Urbana", 17, "Competência 2", "infraestrutura_urbana_2.html"),
(67, "Infraestrutura Urbana", 17, "Competência 3", "infraestrutura_urbana_3.html"),
(68, "Infraestrutura Urbana", 17, "Competência 4", "infraestrutura_urbana_4.html"),
(69, "Design de Interiores", 18, "Competência 1", "design_de_interiores_1.html"),
(70, "Design de Interiores", 18, "Competência 2", "design_de_interiores_2.html"),
(71, "Design de Interiores", 18, "Competência 3", "design_de_interiores_3.html"),
(72, "Design de Interiores", 18, "Competência 4", "design_de_interiores_4.html"),
(73, "Patrimônio Histórico", 19, "Competência 1", "patrimônio_histórico_1.html"),
(74, "Patrimônio Histórico", 19, "Competência 2", "patrimônio_histórico_2.html"),
(75, "Patrimônio Histórico", 19, "Competência 3", "patrimônio_histórico_3.html"),
(76, "Patrimônio Histórico", 19, "Competência 4", "patrimônio_histórico_4.html");