insert into courses
values 
(100, null),
(1, 'Engenharia de Computação'),
(2, 'Engenharia de Controle e Automação'),
(3, 'Engenharia Química'),
(4, 'Engenharia Elétrica'),
(5, 'Engenharia de Produção'),
(6, 'Engenharia Civil'),
(7, 'Engenharia Mecânica'),
(8, 'Arquitetura e Urbanismo');

insert into course_subjects
values
(1, 'Cálculo A'),
(2, 'Metodologia da Pesquisa'),
(3, 'Compiladores'),
(4, 'Banco de Dados 1'),
(5, 'Controle Digital Aplicado'),
(6, 'Sistemas a Eventos Discretos'),
(7, 'Engenharia Bioquímica'),
(8, 'Projetos de Processos Químicos 2'),
(9, 'Acionamentos Elétricos'),
(10, 'Eletromagnetismo'),
(11, 'Comércio Exterior'),
(12, 'Tecnologias Digitais na Produção'),
(13, 'Estruturas de Madeira'),
(14, 'Obras de Terra'),
(15, 'Processos de Soldagem'),
(16, 'Trocadores de Calor'),
(17, 'Intraestrutura Urbana'),
(18, 'Design de Interiores'),
(19, 'Patrimônio Histórico');

insert into offerings
values
(1, 1, 1),
(2, 1, 2),
(3, 1, 3),
(4, 1, 4),
(5, 2, 1),
(6, 2, 2),
(7, 2, 5),
(8, 2, 6),
(9, 3, 1),
(10, 3, 2),
(11, 3, 7),
(12, 3, 8),
(13, 4, 1),
(14, 4, 2),
(15, 4, 9),
(16, 4, 10),
(17, 5, 1),
(18, 5, 2),
(19, 5, 11),
(20, 5, 12),
(21, 6, 1),
(22, 6, 2),
(23, 6, 13),
(24, 6, 14),
(25, 7, 1),
(26, 7, 2),
(27, 7, 15),
(28, 7, 16),
(29, 8, 2),
(30, 8, 17),
(31, 8, 18),
(32, 8, 19);

insert into students
values
(1, '10A.047292', 'Password-0', null, 100, 1),
(2, '20A.752355', 'Password-1', 'Eduardo Fiscina Menezes Moraes', 1, 0),
(3, '10Q.178487', 'Password-2', 'Iago Santana Alfaya', 1, 0),
(4, '67Z.406178', 'Password-3', 'Rodrigo de Jesus Macêdo', 1, 0),
(5, '42L.910086', 'Password-4', 'André Lucas', 1, 0),
(6, '49Z.339516', 'Password-5', 'João Carlos', 6, 0),
(7, '22G.822160', 'Password-6', 'Hayana Fiscina Menezes Dias', 7, 0),
(8, '30F.340348', 'Password-7', 'Carlos Henrique de Brandão', 4, 0),
(9, '50Y.102840', 'Password-8', 'Maria Clara Barbosa', 4, 0);

insert into competencies
values
(1, 'Resolver problemas usando funções matemáticas.', 1),
(2, 'Analisar e interpretar dados através de representações gráficas.', 1),
(3, 'Aplicar o cálculo diferencial e integral para resolver problemas de engenharia.', 1),
(4, 'Desenvolver o pensamento crítico e a resolução de problemas.', 1),
(5, 'Formular perguntas e hipóteses de pesquisa.', 2),
(6, 'Realizar revisões bibliográficas e identificar fontes relevantes.', 2),
(7, 'Selecionar métodos de pesquisa adequados.', 2),
(8, 'Analisar e interpretar dados de pesquisa.', 2),
(9, 'Comunicar os resultados da pesquisa de forma eficaz.', 2),
(10, 'Compreender as diversas etapas do processo de compilação.', 3),
(11, 'Projetar e implementar gramáticas utilizando linguagens formais.', 3),
(12, 'Analisar e otimizar código para eficiência.', 3),
(13, 'Aplicar a tecnologia de compiladores para o desenvolvimento de software.', 3),
(14, 'Desenvolver habilidades de resolução de problemas e análise.', 3),
(15, 'Projetar e implementar bancos de dados relacionais usando SQL.', 4),
(16, 'Normalizar estruturas de dados para minimizar redundância.', 4),
(17, 'Compreender conceitos de integridade e segurança de dados.', 4),
(18, 'Desenvolver habilidades em organização e gerenciamento de dados', 4),
(19, 'Analisar e projetar sistemas de controle para diversas aplicações.', 5),
(20, 'Aplicar princípios de controle por feedback para alcançar o comportamento desejado do sistema.', 5),
(21, 'Compreender conceitos de análise de estabilidade para sistemas de controle.', 5),
(22, 'Projetar e simular sistemas de controle usando ferramentas de software.', 5),
(23, 'Desenvolver habilidades de resolução de problemas no contexto de sistemas automatizados.', 5),
(24, 'Modelar sistemas a eventos discretos usando máquinas de estado e redes de Petri.', 6),
(25, 'Analisar o comportamento do sistema e identificar problemas potenciais.', 6),
(26, 'Aplicar técnicas de controle para sistemas a eventos discretos.', 6),
(27, 'Utilizar ferramentas de software para modelagem e simulação.', 6),
(28, 'Aplicar princípios da química e da biologia para resolver problemas de engenharia.', 7),
(29, 'Compreender biorreatores e processos para produção de bioprodutos.', 7),
(30, 'Analisar e projetar processos de bioconversão.', 7),
(31, 'Desenvolver habilidades em técnicas de laboratório e análise de dados.', 7),
(32, 'Integrar conhecimentos de diversas disciplinas para engenharia de bioprocessos.', 7),
(33, 'Projetar e otimizar processos químicos para aplicações industriais.', 8),
(34, 'Realizar avaliações econômicas e ambientais de processos químicos.', 8),
(35, 'Aplicar software de simulação de processos para análise de processos.', 8),
(36, 'Desenvolver habilidades em gerenciamento de projetos e trabalho em equipe.', 8),
(37, 'Integrar conhecimentos de princípios de engenharia química para projeto de processos.', 8),
(38, 'Compreender e analisar diversos tipos de motores elétricos.', 9),
(39, 'Projetar e selecionar sistemas de controle adequados para motores elétricos.', 9),
(40, 'Aplicar princípios da eletrônica de potência para controle de motores.', 9),
(41, 'Analisar e solucionar falhas em acionamentos elétricos.', 9),
(42, 'Compreender os princípios fundamentais do eletromagnetismo.', 10),
(43, 'Analisar campos elétricos e magnéticos em diversas situações.', 10),
(44, 'Utilizar ferramentas de software para análise de campo eletromagnético.', 10),
(45, 'Desenvolver habilidades de resolução de problemas no contexto de fenômenos eletromagnéticos.', 10),
(46, 'Compreender princípios e regulamentações do comércio internacional.', 11),
(47, 'Analisar mercados internacionais e identificar oportunidades de negócios.', 11),
(48, 'Gerenciar processos de importação e exportação de forma eficaz.', 11),
(49, 'Desenvolver habilidades em negociação e comunicação internacional.', 11),
(50, 'Compreender e utilizar tecnologias digitais em processos de manufatura.', 12),
(51, 'Aplicar conceitos da Indústria 4.0 para otimização da produção.', 12),
(52, 'Integrar ferramentas digitais para gerenciamento da cadeia de suprimentos.', 12),
(53, 'Desenvolver habilidades em análise e interpretação de dados para tomada de decisões na produção.', 12),
(54, 'Gerenciar e implementar transformação digital em ambientes de manufatura.', 12),
(55, 'Compreender as propriedades mecânicas da madeira e seus produtos.', 13),
(56, 'Projetar e analisar estruturas de madeira quanto à resistência e estabilidade.', 13),
(57, 'Aplicar códigos e regulamentos de construção para estruturas de madeira.', 13),
(58, 'Desenvolver habilidades em análise e projeto estrutural usando ferramentas de software.', 13),
(59, 'Compreender mecânica dos solos e estabilidade de taludes.', 14),
(60, 'Projetar e analisar fundações para diferentes tipos de estruturas.', 14),
(61, 'Aplicar técnicas de drenagem e contenção de terras.', 14),
(62, 'Selecionar materiais adequados para obras de terra.', 14),
(63, 'Compreender os diferentes processos de soldagem.', 15),
(64, 'Selecionar o processo de soldagem adequado para diferentes materiais e aplicações.', 15),
(65, 'Realizar soldagem de forma segura e eficiente.', 15),
(66, 'Inspeção e controle de qualidade de soldas.', 15),
(67, 'Compreender os princípios de transferência de calor por condução, convecção e radiação.', 16),
(68, 'Analisar o desempenho de diferentes tipos de trocadores de calor.', 16),
(69, 'Selecionar o trocador de calor adequado para uma aplicação específica.', 16),
(70, 'Dimensionar e projetar trocadores de calor usando softwares específicos.', 16),
(71, 'Compreender os princípios de planejamento e gestão urbana.', 17),
(72, 'Projetar e analisar sistemas de saneamento básico.', 17),
(73, 'Desenvolver soluções para mobilidade urbana e transporte público.', 17),
(74, 'Desenvolver habilidades em planejamento e gestão de infraestrutura urbana sustentável.', 17),
(75, 'Compreender os princípios de design de interiores.', 18),
(76, 'Projetar e planejar layouts de interiores para diferentes funções.', 18),
(77, 'Selecionar materiais, mobiliário e acabamentos adequados para projetos de interiores.', 18),
(78, 'Desenvolver habilidades em representação gráfica e técnicas de apresentação de projetos.', 18),
(79, 'Integrar conceitos de sustentabilidade e acessibilidade em projetos de design de interiores.', 18),
(80, 'Compreender os conceitos de patrimônio cultural e histórico.', 19),
(81, 'Identificar e caracterizar bens tombados e áreas de proteção ambiental.', 19),
(82, 'Desenvolver técnicas para conservação e restauração do patrimônio histórico.', 19),
(83, 'Planejar e executar projetos de valorização e uso sustentável do patrimônio.', 19),
(84, 'Desenvolver habilidades em legislação e políticas públicas para a proteção do patrimônio.', 19);

insert into ovas
values
(1, 'Cálculo A - Competência 1 - 1', 'calculo_a_1_1.html', 1),
(2, 'Cálculo A - Competência 2 - 1', 'calculo_a_2_1.html', 2),
(3, 'Cálculo A - Competência 2 - 2', 'calculo_a_2_2.html', 2),
(4, 'Cálculo A - Competência 3 - 1', 'calculo_a_3_1.html', 3),
(5, 'Cálculo A - Competência 3 - 2', 'calculo_a_3_2.html', 3),
(6, 'Cálculo A - Competência 4 - 1', 'calculo_a_4_1.html', 4),
(7, 'Metodologia da Pesquisa - Competência 1 - 1', 'metodologia_da_pesquisa_1_1.html', 5),
(8, 'Metodologia da Pesquisa - Competência 1 - 2', 'metodologia_da_pesquisa_1_2.html', 5),
(9, 'Metodologia da Pesquisa - Competência 2 - 1', 'metodologia_da_pesquisa_2_1.html', 6),
(10, 'Metodologia da Pesquisa - Competência 2 - 2', 'metodologia_da_pesquisa_2_2.html', 6),
(11, 'Metodologia da Pesquisa - Competência 3 - 1', 'metodologia_da_pesquisa_3_1.html', 7),
(12, 'Metodologia da Pesquisa - Competência 3 - 2', 'metodologia_da_pesquisa_3_2.html', 7),
(13, 'Metodologia da Pesquisa - Competência 4 - 1', 'metodologia_da_pesquisa_4_1.html', 8),
(14, 'Metodologia da Pesquisa - Competência 5 - 1', 'metodologia_da_pesquisa_5_1.html', 9),
(15, 'Compiladores - Competência 1 - 1', 'compiladores_1_1.html', 10),
(16, 'Compiladores - Competência 2 - 1', 'compiladores_2_1.html', 11),
(17, 'Compiladores - Competência 3 - 1', 'compiladores_3_1.html', 12),
(18, 'Compiladores - Competência 4 - 1', 'compiladores_4_1.html', 13),
(19, 'Compiladores - Competência 5 - 1', 'compiladores_5_1.html', 14),
(20, 'Banco de Dados 1 - Competência 1 - 1', 'banco_de_dados_1_1_1.html', 15),
(21, 'Banco de Dados 1 - Competência 2 - 1', 'banco_de_dados_1_2_1.html', 16),
(22, 'Banco de Dados 1 - Competência 3 - 1', 'banco_de_dados_1_3_1.html', 17),
(23, 'Banco de Dados 1 - Competência 3 - 2', 'banco_de_dados_1_3_2.html', 17),
(24, 'Banco de Dados 1 - Competência 4 - 1', 'banco_de_dados_1_4_1.html', 18),
(25, 'Banco de Dados 1 - Competência 4 - 2', 'banco_de_dados_1_4_2.html', 18),
(26, 'Controle Digital Aplicado - Competência 1 - 1', 'controle_digital_aplicado_1_1.html', 19),
(27, 'Controle Digital Aplicado - Competência 2 - 1', 'controle_digital_aplicado_2_1.html', 20),
(28, 'Controle Digital Aplicado - Competência 3 - 1', 'controle_digital_aplicado_3_1.html', 21),
(29, 'Controle Digital Aplicado - Competência 4 - 1', 'controle_digital_aplicado_4_1.html', 22),
(30, 'Controle Digital Aplicado - Competência 5 - 1', 'controle_digital_aplicado_5_1.html', 23),
(31, 'Controle Digital Aplicado - Competência 5 - 2', 'controle_digital_aplicado_5_2.html', 23),
(32, 'Sistemas a Eventos Discretos - Competência 1 - 1', 'sistemas_a_eventos_discretos_1_1.html', 24),
(33, 'Sistemas a Eventos Discretos - Competência 2 - 1', 'sistemas_a_eventos_discretos_2_1.html', 25),
(34, 'Sistemas a Eventos Discretos - Competência 3 - 1', 'sistemas_a_eventos_discretos_3_1.html', 26),
(35, 'Sistemas a Eventos Discretos - Competência 4 - 1', 'sistemas_a_eventos_discretos_4_1.html', 27),
(36, 'Engenharia Bioquímica - Competência 1 - 1', 'engenharia_bioquimica_1_1.html', 28),
(37, 'Engenharia Bioquímica - Competência 2 - 1', 'engenharia_bioquimica_2_1.html', 29),
(38, 'Engenharia Bioquímica - Competência 2 - 2', 'engenharia_bioquimica_2_2.html', 29),
(39, 'Engenharia Bioquímica - Competência 3 - 1', 'engenharia_bioquimica_3_1.html', 30),
(40, 'Engenharia Bioquímica - Competência 4 - 1', 'engenharia_bioquimica_4_1.html', 31),
(41, 'Engenharia Bioquímica - Competência 4 - 2', 'engenharia_bioquimica_4_2.html', 31),
(42, 'Engenharia Bioquímica - Competência 5 - 1', 'engenharia_bioquimica_5_1.html', 32),
(43, 'Projetos de Processos Químicos 2 - Competência 1 - 1', 'projetos_de_processos_quimicos_2_1_1.html', 33),
(44, 'Projetos de Processos Químicos 2 - Competência 1 - 2', 'projetos_de_processos_quimicos_2_1_2.html', 33),
(45, 'Projetos de Processos Químicos 2 - Competência 2 - 1', 'projetos_de_processos_quimicos_2_2_1.html', 34),
(46, 'Projetos de Processos Químicos 2 - Competência 3 - 1', 'projetos_de_processos_quimicos_2_3_1.html', 35),
(47, 'Projetos de Processos Químicos 2 - Competência 4 - 1', 'projetos_de_processos_quimicos_2_4_1.html', 36),
(48, 'Projetos de Processos Químicos 2 - Competência 4 - 2', 'projetos_de_processos_quimicos_2_4_2.html', 36),
(49, 'Projetos de Processos Químicos 2 - Competência 5 - 1', 'projetos_de_processos_quimicos_2_5_1.html', 37),
(50, 'Acionamentos Elétricos - Competência 1 - 1', 'acionamentos_eletricos_1_1.html', 38),
(51, 'Acionamentos Elétricos - Competência 2 - 1', 'acionamentos_eletricos_2_1.html', 39),
(52, 'Acionamentos Elétricos - Competência 2 - 2', 'acionamentos_eletricos_2_2.html', 39),
(53, 'Acionamentos Elétricos - Competência 3 - 1', 'acionamentos_eletricos_3_1.html', 40),
(54, 'Acionamentos Elétricos - Competência 4 - 1', 'acionamentos_eletricos_4_1.html', 41),
(55, 'Eletromagnetismo - Competência 1 - 1', 'eletromagnetismo_1_1.html', 42),
(56, 'Eletromagnetismo - Competência 2 - 1', 'eletromagnetismo_2_1.html', 43),
(57, 'Eletromagnetismo - Competência 3 - 1', 'eletromagnetismo_3_1.html', 44),
(58, 'Eletromagnetismo - Competência 3 - 2', 'eletromagnetismo_3_2.html', 44),
(59, 'Eletromagnetismo - Competência 4 - 1', 'eletromagnetismo_4_1.html', 45),
(60, 'Comércio Exterior - Competência 1 - 1', 'comercio_exterior_1_1.html', 46),
(61, 'Comércio Exterior - Competência 2 - 1', 'comercio_exterior_2_1.html', 47),
(62, 'Comércio Exterior - Competência 2 - 2', 'comercio_exterior_2_2.html', 47),
(63, 'Comércio Exterior - Competência 3 - 1', 'comercio_exterior_3_1.html', 48),
(64, 'Comércio Exterior - Competência 3 - 2', 'comercio_exterior_3_2.html', 48),
(65, 'Comércio Exterior - Competência 4 - 1', 'comercio_exterior_4_1.html', 49),
(66, 'Comércio Exterior - Competência 4 - 2', 'comercio_exterior_4_2.html', 49),
(67, 'Tecnologias Digitais na Produção - Competência 1 - 1', 'tecnologias_digitais_na_producao_1_1.html', 50),
(68, 'Tecnologias Digitais na Produção - Competência 2 - 1', 'tecnologias_digitais_na_producao_2_1.html', 51),
(69, 'Tecnologias Digitais na Produção - Competência 3 - 1', 'tecnologias_digitais_na_producao_3_1.html', 52),
(70, 'Tecnologias Digitais na Produção - Competência 3 - 2', 'tecnologias_digitais_na_producao_3_2.html', 52),
(71, 'Tecnologias Digitais na Produção - Competência 4 - 1', 'tecnologias_digitais_na_producao_4_1.html', 53),
(72, 'Tecnologias Digitais na Produção - Competência 5 - 1', 'tecnologias_digitais_na_producao_5_1.html', 54),
(73, 'Estruturas de Madeira - Competência 1 - 1', 'estruturas_de_madeira_1_1.html', 55),
(74, 'Estruturas de Madeira - Competência 2 - 1', 'estruturas_de_madeira_2_1.html', 56),
(75, 'Estruturas de Madeira - Competência 2 - 2', 'estruturas_de_madeira_2_2.html', 56),
(76, 'Estruturas de Madeira - Competência 3 - 1', 'estruturas_de_madeira_3_1.html', 57),
(77, 'Estruturas de Madeira - Competência 4 - 1', 'estruturas_de_madeira_4_1.html', 58),
(78, 'Obras de Terra - Competência 1 - 1', 'obras_de_terra_1_1.html', 59),
(79, 'Obras de Terra - Competência 1 - 2', 'obras_de_terra_1_2.html', 59),
(80, 'Obras de Terra - Competência 2 - 1', 'obras_de_terra_2_1.html', 60),
(81, 'Obras de Terra - Competência 3 - 1', 'obras_de_terra_3_1.html', 61),
(82, 'Obras de Terra - Competência 4 - 1', 'obras_de_terra_4_1.html', 62),
(83, 'Processos de Soldagem - Competência 1 - 1', 'processos_de_soldagem_1_1.html', 63),
(84, 'Processos de Soldagem - Competência 2 - 1', 'processos_de_soldagem_2_1.html', 64),
(85, 'Processos de Soldagem - Competência 3 - 1', 'processos_de_soldagem_3_1.html', 65),
(86, 'Processos de Soldagem - Competência 3 - 2', 'processos_de_soldagem_3_2.html', 65),
(87, 'Processos de Soldagem - Competência 4 - 1', 'processos_de_soldagem_4_1.html', 66),
(88, 'Trocadores de Calor - Competência 1 - 1', 'trocadores_de_calor_1_1.html', 67),
(89, 'Trocadores de Calor - Competência 2 - 1', 'trocadores_de_calor_2_1.html', 68),
(90, 'Trocadores de Calor - Competência 2 - 2', 'trocadores_de_calor_2_2.html', 68),
(91, 'Trocadores de Calor - Competência 3 - 1', 'trocadores_de_calor_3_1.html', 69),
(92, 'Trocadores de Calor - Competência 3 - 2', 'trocadores_de_calor_3_2.html', 69),
(93, 'Trocadores de Calor - Competência 4 - 1', 'trocadores_de_calor_4_1.html', 70),
(94, 'Infraestrutura Urbana - Competência 1 - 1', 'infraestrutura_urbana_1_1.html', 71),
(95, 'Infraestrutura Urbana - Competência 2 - 1', 'infraestrutura_urbana_2_1.html', 72),
(96, 'Infraestrutura Urbana - Competência 3 - 1', 'infraestrutura_urbana_3_1.html', 73),
(97, 'Infraestrutura Urbana - Competência 4 - 1', 'infraestrutura_urbana_4_1.html', 74),
(98, 'Design de Interiores - Competência 1 - 1', 'design_de_interiores_1_1.html', 75),
(99, 'Design de Interiores - Competência 2 - 1', 'design_de_interiores_2_1.html', 76),
(100, 'Design de Interiores - Competência 3 - 1', 'design_de_interiores_3_1.html', 77),
(101, 'Design de Interiores - Competência 3 - 2', 'design_de_interiores_3_2.html', 77),
(102, 'Design de Interiores - Competência 4 - 1', 'design_de_interiores_4_1.html', 78),
(103, 'Design de Interiores - Competência 5 - 1', 'design_de_interiores_5_1.html', 79),
(104, 'Design de Interiores - Competência 5 - 2', 'design_de_interiores_5_2.html', 79),
(105, 'Patrimônio Histórico - Competência 1 - 1', 'patrimonio_historico_1_1.html', 80),
(106, 'Patrimônio Histórico - Competência 2 - 1', 'patrimonio_historico_2_1.html', 81),
(107, 'Patrimônio Histórico - Competência 3 - 1', 'patrimonio_historico_3_1.html', 82),
(108, 'Patrimônio Histórico - Competência 4 - 1', 'patrimonio_historico_4_1.html', 83),
(109, 'Patrimônio Histórico - Competência 5 - 1', 'patrimonio_historico_5_1.html', 84);

set identity_insert interactions on;